import sys
from wsgiref.util import application_uri
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(False)
        MainWindow.resize(325, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(325, 450))
        self.widget.setStyleSheet("widget{background-color: rgb(227, 227, 227);}")
        self.widget.setObjectName("widget")
        self.label_logo = QtWidgets.QLabel(self.widget)
        self.label_logo.setEnabled(False)
        self.label_logo.setGeometry(QtCore.QRect(210, 10, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setText("")
    #"c:\\INTERFACES\\LOGO APP\\REQVISION
        
        self.label_logo.setPixmap(QtGui.QPixmap("c:\\INTERFACES\\LOGO APP\\REQVISION_-_somente_logo-removebg-preview.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 60, 131, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\INTERFACES\\LOGO APP\\USER-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_logar = QtWidgets.QPushButton(self.widget)
        self.pushButton_logar.setGeometry(QtCore.QRect(50, 340, 200, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logar.sizePolicy().hasHeightForWidth())
        self.pushButton_logar.setSizePolicy(sizePolicy)
        self.pushButton_logar.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logar.setFont(font)
        self.pushButton_logar.setStyleSheet("background-color: rgb(87, 87, 94);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255)")
        self.pushButton_logar.setObjectName("pushButton_logar")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(10, 200, 281, 131))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.UsertextEdit = QtWidgets.QTextEdit(self.widget1)
        self.UsertextEdit.setEnabled(False)
        self.UsertextEdit.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.UsertextEdit.setFont(font)
        self.UsertextEdit.setStyleSheet("background-color: rgb(156, 156, 163);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
        self.UsertextEdit.setObjectName("UsertextEdit")
        self.gridLayout.addWidget(self.UsertextEdit, 0, 1, 1, 1)
        self.label_us_2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_us_2.sizePolicy().hasHeightForWidth())
        self.label_us_2.setSizePolicy(sizePolicy)
        self.label_us_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_us_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_us_2.setAutoFillBackground(False)
        self.label_us_2.setStyleSheet("radius-border: 30px;")
        self.label_us_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_us_2.setLineWidth(2)
        self.label_us_2.setMidLineWidth(2)
        self.label_us_2.setText("")
        self.label_us_2.setPixmap(QtGui.QPixmap("c:\\INTERFACES\\LOGO APP\\CADEADO.png"))
        self.label_us_2.setScaledContents(True)
        self.label_us_2.setObjectName("label_us_2")
        self.gridLayout.addWidget(self.label_us_2, 1, 0, 1, 1)
        self.label_us = QtWidgets.QLabel(self.widget1)
        self.label_us.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_us.sizePolicy().hasHeightForWidth())
        self.label_us.setSizePolicy(sizePolicy)
        self.label_us.setMaximumSize(QtCore.QSize(50, 50))
        self.label_us.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_us.setAutoFillBackground(False)
        self.label_us.setStyleSheet("radius-border: 30px;")
        self.label_us.setFrameShape(QtWidgets.QFrame.Box)
        self.label_us.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_us.setLineWidth(2)
        self.label_us.setMidLineWidth(2)
        self.label_us.setText("")
        self.label_us.setPixmap(QtGui.QPixmap("c:\\INTERFACES\\LOGO APP\\png-transparent-computer-icons-user-profile-login-user-heroes-sphere-black-thumbnail-removebg-preview.png"))
        self.label_us.setScaledContents(True)
        self.label_us.setObjectName("label_us")
        self.gridLayout.addWidget(self.label_us, 0, 0, 1, 1)
        self.SenhaextEdit = QtWidgets.QTextEdit(self.widget1)
        self.SenhaextEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SenhaextEdit.sizePolicy().hasHeightForWidth())
        self.SenhaextEdit.setSizePolicy(sizePolicy)
        self.SenhaextEdit.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.SenhaextEdit.setFont(font)
        self.SenhaextEdit.setStyleSheet("background-color: rgb(156, 156, 163);\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);")
        self.SenhaextEdit.setObjectName("SenhaextEdit")
        self.gridLayout.addWidget(self.SenhaextEdit, 1, 1, 1, 1)
        self.label_us.raise_()
        self.UsertextEdit.raise_()
        self.SenhaextEdit.raise_()
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inicio"))
        self.pushButton_logar.setText(_translate("MainWindow", "Login"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
